### ISSUE TITLE
Watch Error on Windows

### ISSUE THREAD

**Issue by hacdias** [caddyserver/caddydev#6]
Command: `caddydev --source D:\Code\Go\src\github.com\hacdias\caddy-hugo hugo`

Error:

```
Watcher enabled, watching for file changes.
Building...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0x4079c4]

goroutine 1 [running]:
main.watchChanges.func1(0xc0821a90e0, 0x104, 0x0, 0x0, 0xa843f8, 0xc0821a6b10, 0x0, 0x0)
        D:/Code/Go/src/github.com/caddyserver/caddydev/watch.go:36 +0x44
path/filepath.walk(0xc0821a4d00, 0xf7, 0xa84420, 0xc0821ce480, 0xc0820f9bb8, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:370 +0x41c
path/filepath.walk(0xc082187590, 0xed, 0xa84420, 0xc0821ce300, 0xc0820f9bb8, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc0821acfc0, 0xe0, 0xa84420, 0xc0821ce180, 0xc0820f9bb8, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc0821ac9a0, 0xd8, 0xa84420, 0xc0821ce000, 0xc0820f9bb8, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc0821aec30, 0xcb, 0xa84420, 0xc0821b1e60, 0xc0820f9bb8, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc0821c6780, 0xc0, 0xa84420, 0xc0821b1ce0, 0xc0820f9bb8, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc0821c6240, 0xb3, 0xa84420, 0xc0821b1b60, 0xc0820f9bb8, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc0821a26e0, 0xa6, 0xa84420, 0xc0821b1980, 0xc0820f9bb8, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc08219e8c0, 0x99, 0xa84420, 0xc0821b1800, 0xc0820f9bb8, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc08219e460, 0x93, 0xa84420, 0xc0821b1680, 0xc0820f9bb8, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc0821aa750, 0x86, 0xa84420, 0xc0821b1500, 0xc0820f9bb8, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc082189100, 0x80, 0xa84420, 0xc0821b1380, 0xc0820f9bb8, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc082188d80, 0x73, 0xa84420, 0xc0821b1200, 0xc0820f9bb8, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc082198a80, 0x6e, 0xa84420, 0xc0821b1080, 0xc0820f9bb8, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc082198770, 0x61, 0xa84420, 0xc0821b0f00, 0xc0820f9bb8, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc0821b0ba0, 0x55, 0xa84420, 0xc0821b0c00, 0xc0820f9bb8, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc08219abe0, 0x48, 0xa84420, 0xc0821b0960, 0xc0820f9bb8, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc082185780, 0x3d, 0xa84420, 0xc0821b0780, 0xc0820f9bb8, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc0820561b0, 0x2c, 0xa84420, 0xc082150000, 0xc0820f9bb8, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:374 +0x503
path/filepath.Walk(0xc0820561b0, 0x2c, 0xc0820f9bb8, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:396 +0xe8
main.watchChanges(0x27702f0, 0xc08211a1c0, 0xc0820561b0, 0x2c, 0xc082138780, 0x0, 0x0)
        D:/Code/Go/src/github.com/caddyserver/caddydev/watch.go:49 +0x11b
main.main()
        D:/Code/Go/src/github.com/caddyserver/caddydev/main.go:147 +0xae0

goroutine 5 [syscall]:
os/signal.loop()
        c:/go/src/os/signal/signal_unix.go:22 +0x1f
created by os/signal.init.1
        c:/go/src/os/signal/signal_unix.go:28 +0x3e

goroutine 17 [select]:
main.trapInterrupts.func1(0xc082138720, 0xc0821386c0, 0xc082138660)
        D:/Code/Go/src/github.com/caddyserver/caddydev/cleanup.go:17 +0x2f1
created by main.trapInterrupts
        D:/Code/Go/src/github.com/caddyserver/caddydev/cleanup.go:28 +0x1fb

goroutine 18 [syscall, locked to thread]:
syscall.Syscall(0x7ffff225d840, 0x2, 0x280, 0xffffffff, 0x0, 0xc08214d020, 0x40b8cc, 0x43b5b2)
        c:/go/src/runtime/syscall_windows.go:128 +0x5c
syscall.WaitForSingleObject(0x280, 0xffffffff, 0xc08213f9a0, 0x0, 0x0)
        c:/go/src/syscall/zsyscall_windows.go:690 +0x6f
os.(*Process).wait(0xc08209d5a0, 0x0, 0x0, 0x0)
        c:/go/src/os/exec_windows.go:18 +0xa2
os.(*Process).Wait(0xc08209d5a0, 0x4, 0x0, 0x0)
        c:/go/src/os/doc.go:45 +0x34
os/exec.(*Cmd).Wait(0xc082485400, 0x0, 0x0)
        c:/go/src/os/exec/exec.go:380 +0x21e
os/exec.(*Cmd).Run(0xc082485400, 0x0, 0x0)
        c:/go/src/os/exec/exec.go:258 +0x6b
github.com/mholt/custombuild.(*Builder).build(0xc08211a200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0820e5d80, 0x37, 0x0, ...)
        D:/Code/Go/src/github.com/mholt/custombuild/builder.go:268 +0x6c6
github.com/mholt/custombuild.(*Builder).Build(0xc08211a200, 0x0, 0x0, 0x0, 0x0, 0xc0820e5d80, 0x37, 0x0, 0x0, 0x0, ...)
        D:/Code/Go/src/github.com/mholt/custombuild/builder.go:231 +0xc7
main.(*caddyApp).Build(0xc08211a1c0, 0x0, 0x0)
        D:/Code/Go/src/github.com/caddyserver/caddydev/app.go:87 +0x176
main.main.func1(0xc08205a000, 0xc082002490, 0x27702f0, 0xc08211a1c0, 0xc082138660)
        D:/Code/Go/src/github.com/caddyserver/caddydev/main.go:117 +0x55
created by main.main
        D:/Code/Go/src/github.com/caddyserver/caddydev/main.go:142 +0x97d

goroutine 19 [syscall, locked to thread]:
syscall.Syscall6(0x7ffff224d5c0, 0x5, 0x21c, 0xc082141b40, 0xc082141b44, 0xc082141ba8, 0xffffffff, 0x0, 0xc082141d60, 0xc082141a01, ...)
        c:/go/src/runtime/syscall_windows.go:139 +0x5c
syscall.GetQueuedCompletionStatus(0x21c, 0xc082141b40, 0xc082141b44, 0xc082141ba8, 0xffffffff, 0x0, 0x0)
        c:/go/src/syscall/zsyscall_windows.go:526 +0x99
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc0820e5e00)
        D:/Code/Go/src/gopkg.in/fsnotify.v1/windows.go:381 +0x122
created by gopkg.in/fsnotify%2ev1.NewWatcher
        D:/Code/Go/src/gopkg.in/fsnotify.v1/windows.go:46 +0x37e

goroutine 15 [syscall, locked to thread]:
syscall.Syscall6(0x7ffff225dbd0, 0x5, 0x264, 0xc082182000, 0x200, 0xc08246dc2c, 0x0, 0x0, 0x734140, 0x0, ...)
        c:/go/src/runtime/syscall_windows.go:139 +0x5c
syscall.ReadFile(0x264, 0xc082182000, 0x200, 0x200, 0xc08246dc2c, 0x0, 0x0, 0x0)
        c:/go/src/syscall/zsyscall_windows.go:283 +0xcc
syscall.Read(0x264, 0xc082182000, 0x200, 0x200, 0x4317ab, 0x0, 0x0)
        c:/go/src/syscall/syscall_windows.go:299 +0x7c
os.(*File).read(0xc082478530, 0xc082182000, 0x200, 0x200, 0x0, 0x0, 0x0)
        c:/go/src/os/file_windows.go:300 +0x153
os.(*File).Read(0xc082478530, 0xc082182000, 0x200, 0x200, 0x0, 0x0, 0x0)
        c:/go/src/os/file.go:95 +0x91
bytes.(*Buffer).ReadFrom(0xc08214e3f0, 0xb40000, 0xc082478530, 0x0, 0x0, 0x0)
        c:/go/src/bytes/buffer.go:173 +0x246
io.copyBuffer(0xa84470, 0xc08214e3f0, 0xb40000, 0xc082478530, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/io/io.go:375 +0x187
io.Copy(0xa84470, 0xc08214e3f0, 0xb40000, 0xc082478530, 0x0, 0x0, 0x0)
        c:/go/src/io/io.go:351 +0x6b
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
        c:/go/src/os/exec/exec.go:232 +0x92
os/exec.(*Cmd).Start.func1(0xc082485400, 0xc08209d520)
        c:/go/src/os/exec/exec.go:340 +0x24
created by os/exec.(*Cmd).Start
        c:/go/src/os/exec/exec.go:341 +0xa8a
```

I saw I could do the same way but...

**Comment by abiosoft** [comment]
Oops. Thanks for reporting this.

Because of you, I will always test on Windows now. You can disable filewatcher for now till it is fixed.

**Comment by hacdias** [comment]
You're welcome and thank you too. :+1:
